import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { cn } from '@/lib/utils';
import Navbar from '@/components/Navbar';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen w-full bg-white text-black flex-col',
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          { 'debug-screens': process.env.NODE_ENV === 'development' }
        )}
      >
        {/* navBar */}
        <nav className='w-full flex-auto'>
          {' '}
          <Navbar />
        </nav>
        {/* mainPage */}
        <div className='p-2 w-full flex-auto'>{children}</div>
      </body>
    </html>
  );
}
